# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

# DO NOT EDIT. Generated by protoc-gen-pydantic.

from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field

from ._proto_types import _ProtoEnum


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class AttackRerunFilter(_ProtoEnum):
    """
    AttackRerunFilter limits a restarted job to selected groups of attacks from
    the source job. When no filters are specified, every attack is rerun.
    """

    ATTACK_RERUN_FILTER_UNSPECIFIED = ("ATTACK_RERUN_FILTER_UNSPECIFIED", 0)
    # The attack succeeded against the target; the target failed to prevent it.
    ATTACK_RERUN_FILTER_ATTACK_SUCCESSFUL = ("ATTACK_RERUN_FILTER_ATTACK_SUCCESSFUL", 1)
    # The attack loop produced an error and skipped the attack.
    ATTACK_RERUN_FILTER_ATTACK_SKIPPED = ("ATTACK_RERUN_FILTER_ATTACK_SKIPPED", 2)


class PageRequest(_ProtoModel):
    """
    PageRequest is the request-side pagination input shared across ai_validation list RPCs.
    """

    # Maximum number of items to return (1-100).
    page_size: int = _Field(
        default=0,
        description="Maximum number of items to return (1-100).",
    )
    # Offset for pagination. 0 for the first page.
    offset: int = _Field(
        default=0,
        description="Offset for pagination. 0 for the first page.",
    )


class PageInfo(_ProtoModel):
    """
    PageInfo is the response-side pagination metadata shared across ai_validation list RPCs.
    """

    # Number of items returned in this response.
    page_size: int = _Field(
        default=0,
        description="Number of items returned in this response.",
    )
    # Offset used for this response.
    offset: int = _Field(
        default=0,
        description="Offset used for this response.",
    )
    # Offset to use to fetch the next page. 0 when no further pages exist.
    next_offset: int = _Field(
        default=0,
        description="Offset to use to fetch the next page. 0 when no further pages exist.",
    )
    # Total number of items available across all pages.
    total: int = _Field(
        default=0,
        description="Total number of items available across all pages.",
    )
