# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

# DO NOT EDIT. Generated by protoc-gen-pydantic.

from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field

from ._proto_types import ProtoTimestamp, _EnumValueOptions, _ProtoEnum

from .common_pydantic import PageRequest

from .common_pydantic import PageInfo

from .common_pydantic import AttackRerunFilter

from aidefense.pydantic.validation.ai_validation_service.v1.ai_validation_service_pydantic import (
    RedTeamReport,
)


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class RedTeamJobSortField(_ProtoEnum):
    """
    Sortable fields for listing red team jobs.
    """

    RED_TEAM_JOB_SORT_FIELD_UNSPECIFIED = ("RED_TEAM_JOB_SORT_FIELD_UNSPECIFIED", 0)
    RED_TEAM_JOB_SORT_FIELD_CREATED_AT = ("RED_TEAM_JOB_SORT_FIELD_CREATED_AT", 1)
    RED_TEAM_JOB_SORT_FIELD_STATUS = ("RED_TEAM_JOB_SORT_FIELD_STATUS", 2)
    RED_TEAM_JOB_SORT_FIELD_STARTED_AT = ("RED_TEAM_JOB_SORT_FIELD_STARTED_AT", 3)
    RED_TEAM_JOB_SORT_FIELD_COMPLETED_AT = ("RED_TEAM_JOB_SORT_FIELD_COMPLETED_AT", 4)


class SortDirection(_ProtoEnum):
    """
    Sort direction for ordering results.
    """

    SORT_DIRECTION_UNSPECIFIED = ("SORT_DIRECTION_UNSPECIFIED", 0)
    SORT_DIRECTION_ASC = ("SORT_DIRECTION_ASC", 1)
    SORT_DIRECTION_DESC = ("SORT_DIRECTION_DESC", 2)


class RedTeamJobStatus(_ProtoEnum):
    """
    Job status for red team jobs.
    """

    RED_TEAM_JOB_STATUS_UNSPECIFIED = ("RED_TEAM_JOB_STATUS_UNSPECIFIED", 0)
    RED_TEAM_JOB_STATUS_CREATED = ("RED_TEAM_JOB_STATUS_CREATED", 1)
    RED_TEAM_JOB_STATUS_IN_PROGRESS = ("RED_TEAM_JOB_STATUS_IN_PROGRESS", 2)
    RED_TEAM_JOB_STATUS_COMPLETED = ("RED_TEAM_JOB_STATUS_COMPLETED", 3)
    RED_TEAM_JOB_STATUS_FAILED = ("RED_TEAM_JOB_STATUS_FAILED", 4)
    RED_TEAM_JOB_STATUS_PAUSED = (
        "RED_TEAM_JOB_STATUS_PAUSED",
        5,
        _EnumValueOptions(
            value_visibility=None,
        ),
    )
    RED_TEAM_JOB_STATUS_CANCELLED = (
        "RED_TEAM_JOB_STATUS_CANCELLED",
        6,
        _EnumValueOptions(
            value_visibility=None,
        ),
    )


class Industry(_ProtoEnum):
    """
    Industry vertical used to bias red team attack generation.
    UNSPECIFIED falls back to INDUSTRY_DEFAULT on the data plane.
    """

    INDUSTRY_UNSPECIFIED = ("INDUSTRY_UNSPECIFIED", 0)
    INDUSTRY_DEFAULT = ("INDUSTRY_DEFAULT", 1)
    INDUSTRY_HEALTHCARE = ("INDUSTRY_HEALTHCARE", 2)
    INDUSTRY_FINANCIAL_SERVICES = ("INDUSTRY_FINANCIAL_SERVICES", 3)
    INDUSTRY_TECHNOLOGY = ("INDUSTRY_TECHNOLOGY", 4)
    INDUSTRY_RETAIL = ("INDUSTRY_RETAIL", 5)
    INDUSTRY_EDUCATION = ("INDUSTRY_EDUCATION", 6)
    INDUSTRY_GOVERNMENT = ("INDUSTRY_GOVERNMENT", 7)
    INDUSTRY_MANUFACTURING = ("INDUSTRY_MANUFACTURING", 8)
    INDUSTRY_ENERGY = ("INDUSTRY_ENERGY", 9)
    INDUSTRY_EQUIPMENT_RENTAL = ("INDUSTRY_EQUIPMENT_RENTAL", 10)
    INDUSTRY_HUMAN_CAPITAL_MANAGEMENT = ("INDUSTRY_HUMAN_CAPITAL_MANAGEMENT", 11)


class PauseRedTeamJobRequest(_ProtoModel):
    """
    PauseRedTeamJobRequest identifies a red team job to pause.
    """

    job_id: str = _Field(default="")


class PauseRedTeamJobResponse(_ProtoModel):
    """
    PauseRedTeamJobResponse is empty on success.
    """

    pass


class ResumeRedTeamJobRequest(_ProtoModel):
    """
    ResumeRedTeamJobRequest identifies a paused red team job and controls how its
    work is resumed.
    """

    job_id: str = _Field(default="")
    options: "ResumeRedTeamJobOptions | None" = _Field(default=None)


class ResumeRedTeamJobResponse(_ProtoModel):
    """
    ResumeRedTeamJobResponse is empty on success.
    """

    pass


class CancelRedTeamJobRequest(_ProtoModel):
    """
    CancelRedTeamJobRequest identifies a red team job to cancel.
    """

    job_id: str = _Field(default="")


class CancelRedTeamJobResponse(_ProtoModel):
    """
    CancelRedTeamJobResponse is empty on success.
    """

    pass


class RestartRedTeamJobRequest(_ProtoModel):
    """
    RestartRedTeamJobRequest identifies a cancelled red team job to restart as a
    new job.
    """

    # Unique identifier of the source job.
    job_id: str = _Field(
        default="",
        description="Unique identifier of the source job.",
    )
    options: "RestartRedTeamJobOptions | None" = _Field(default=None)


class RestartRedTeamJobResponse(_ProtoModel):
    """
    RestartRedTeamJobResponse identifies the new red team job.
    """

    job_id: str = _Field(default="")


class RedTeamJobSummary(_ProtoModel):
    """
    Summary of a red team job returned in list responses.
    """

    # Unique identifier for the red team job.
    job_id: str = _Field(
        default="",
        description="Unique identifier for the red team job.",
    )
    # Human-readable name supplied at job creation.
    name: str = _Field(
        default="",
        description="Human-readable name supplied at job creation.",
    )
    # Description supplied at job creation.
    description: str = _Field(
        default="",
        description="Description supplied at job creation.",
    )
    # Name of the target this job ran against (snapshot from the target at list time).
    target_name: str = _Field(
        default="",
        description="Name of the target this job ran against (snapshot from the target at list time).",
    )
    # Name of the validation profile this job used (snapshot from the profile at list time).
    profile_name: str = _Field(
        default="",
        description="Name of the validation profile this job used (snapshot from the profile at list time).",
    )
    # Current status of the red team job.
    status: "RedTeamJobStatus | None" = _Field(
        default=None,
        description="Current status of the red team job.",
    )
    # Populated only when status is FAILED.
    error_message: str | None = _Field(
        default=None,
        description="Populated only when status is FAILED.",
    )
    created_at: ProtoTimestamp | None = _Field(default=None)
    started_at: ProtoTimestamp | None = _Field(default=None)
    completed_at: ProtoTimestamp | None = _Field(default=None)
    # Industry vertical the job was run under.
    industry: "Industry | None" = _Field(
        default=None,
        description="Industry vertical the job was run under.",
    )
    # ID of the target this job ran against. Enables re-running (retry) the job.
    # Optional (unset) because the target may have been deleted since the job ran;
    # when present it must be a valid UUID.
    target_id: str | None = _Field(
        default=None,
        description="ID of the target this job ran against. Enables re-running (retry) the job.\nOptional (unset) because the target may have been deleted since the job ran;\nwhen present it must be a valid UUID.",
    )
    # ID of the validation profile this job used. Enables re-running (retry) the job.
    # Optional (unset) because the profile may have been deleted since the job ran;
    # when present it must be a valid UUID.
    profile_id: str | None = _Field(
        default=None,
        description="ID of the validation profile this job used. Enables re-running (retry) the job.\nOptional (unset) because the profile may have been deleted since the job ran;\nwhen present it must be a valid UUID.",
    )


class ListRedTeamJobsRequest(_ProtoModel):
    """
    Request to list red team jobs with offset-based pagination, filtering, and sorting.
    """

    # Pagination input.
    page: "PageRequest | None" = _Field(
        default=None,
        description="Pagination input.",
    )
    # Field to sort by. Defaults to CREATED_AT.
    sort_field: "RedTeamJobSortField | None" = _Field(
        default=None,
        description="Field to sort by. Defaults to CREATED_AT.",
    )
    # Sort direction. Defaults to DESC.
    sort_direction: "SortDirection | None" = _Field(
        default=None,
        description="Sort direction. Defaults to DESC.",
    )
    # Filter by job status.
    status: "RedTeamJobStatus | None" = _Field(
        default=None,
        description="Filter by job status.",
    )
    # Return only jobs created at or after this timestamp.
    created_after: ProtoTimestamp | None = _Field(
        default=None,
        description="Return only jobs created at or after this timestamp.",
    )
    # Return only jobs created at or before this timestamp.
    created_before: ProtoTimestamp | None = _Field(
        default=None,
        description="Return only jobs created at or before this timestamp.",
    )
    # Pattern match across name, description, target name, profile name.
    search: str | None = _Field(
        default=None,
        description="Pattern match across name, description, target name, profile name.",
    )


class ListRedTeamJobsResponse(_ProtoModel):
    """
    Response for listing red team jobs.
    """

    jobs: "list[RedTeamJobSummary]" = _Field(
        default_factory=list,
    )
    # Pagination metadata.
    page_info: "PageInfo | None" = _Field(
        default=None,
        description="Pagination metadata.",
    )


class GetRedTeamJobRequest(_ProtoModel):
    """
    Request to get the full details of a red team job.
    """

    job_id: str = _Field(default="")


class GetRedTeamJobResponse(_ProtoModel):
    """
    Full details of a red team job.
    """

    # Unique identifier for the red team job.
    job_id: str = _Field(
        default="",
        description="Unique identifier for the red team job.",
    )
    # Human-readable name supplied at job creation.
    name: str = _Field(
        default="",
        description="Human-readable name supplied at job creation.",
    )
    # Description supplied at job creation.
    description: str = _Field(
        default="",
        description="Description supplied at job creation.",
    )
    # Name of the target this job ran against.
    target_name: str = _Field(
        default="",
        description="Name of the target this job ran against.",
    )
    # Name of the validation profile this job used.
    profile_name: str = _Field(
        default="",
        description="Name of the validation profile this job used.",
    )
    # Current status of the red team job.
    status: "RedTeamJobStatus | None" = _Field(
        default=None,
        description="Current status of the red team job.",
    )
    # Populated only when status is FAILED.
    error_message: str | None = _Field(
        default=None,
        description="Populated only when status is FAILED.",
    )
    created_at: ProtoTimestamp | None = _Field(default=None)
    started_at: ProtoTimestamp | None = _Field(default=None)
    completed_at: ProtoTimestamp | None = _Field(default=None)
    # Industry vertical the job was run under.
    industry: "Industry | None" = _Field(
        default=None,
        description="Industry vertical the job was run under.",
    )
    # ID of the target this job ran against. Enables re-running (retry) the job.
    # Optional (unset) because the target may have been deleted since the job ran;
    # when present it must be a valid UUID.
    target_id: str | None = _Field(
        default=None,
        description="ID of the target this job ran against. Enables re-running (retry) the job.\nOptional (unset) because the target may have been deleted since the job ran;\nwhen present it must be a valid UUID.",
    )
    # ID of the validation profile this job used. Enables re-running (retry) the job.
    # Optional (unset) because the profile may have been deleted since the job ran;
    # when present it must be a valid UUID.
    profile_id: str | None = _Field(
        default=None,
        description="ID of the validation profile this job used. Enables re-running (retry) the job.\nOptional (unset) because the profile may have been deleted since the job ran;\nwhen present it must be a valid UUID.",
    )


class RedTeamJobConfig(_ProtoModel):
    """
    RedTeamJobConfig contains the updatable fields for a red team job.
    Fields are optional so that validation rules only fire when a field is actually set.
    """

    # name is the human-readable name of the red team job
    name: str | None = _Field(
        default=None,
        description="name is the human-readable name of the red team job",
    )
    # description of the red team job
    description: str | None = _Field(
        default=None,
        description="description of the red team job",
    )


class UpdateRedTeamJobRequest(_ProtoModel):
    # job_id identifies which job to update (bound from URL path)
    job_id: str = _Field(
        default="",
        description="job_id identifies which job to update (bound from URL path)",
    )
    # Field mask specifies which fields in `job` to update.
    # If omitted or empty, grpc-gateway will auto-populate it from the JSON keys present in the request body.
    update_mask: list[str] | None = _Field(
        default=None,
        description="Field mask specifies which fields in `job` to update.\nIf omitted or empty, grpc-gateway will auto-populate it from the JSON keys present in the request body.",
    )
    # The red team job fields to update (HTTP body)
    job: "RedTeamJobConfig | None" = _Field(
        default=None,
        description="The red team job fields to update (HTTP body)",
    )


class UpdateRedTeamJobResponse(_ProtoModel):
    pass


class DeleteRedTeamJobRequest(_ProtoModel):
    """
    Request to soft-delete a red team job.
    """

    job_id: str = _Field(default="")


class DeleteRedTeamJobResponse(_ProtoModel):
    """
    Response for deleting a red team job. Empty on success.
    """

    pass


class StartRedTeamJobResponse(_ProtoModel):
    """
    Response for starting a red team test against an application. Contains the job ID of the started test.
    """

    job_id: str = _Field(default="")


class StartAdaptiveRedTeamRequest(_ProtoModel):
    """
    Request to start an adaptive red team test against any target type.
    Connection details are resolved from the target; test configuration from the profile.
    """

    # The ID of the target to test. All connection details are resolved server-side from this target.
    target_id: str = _Field(
        default="",
        description="The ID of the target to test. All connection details are resolved server-side from this target.",
    )
    # The ID of the validation profile to use. Test configuration (language,
    # content categories, custom goals, multi-turn) is resolved from this profile.
    profile_id: str = _Field(
        default="",
        description="The ID of the validation profile to use. Test configuration (language,\ncontent categories, custom goals, multi-turn) is resolved from this profile.",
    )
    # Human-readable name for this red team test run.
    name: str = _Field(
        default="",
        description="Human-readable name for this red team test run.",
    )
    # Optional description of this red team test run.
    description: str = _Field(
        default="",
        description="Optional description of this red team test run.",
    )
    # When true, model outputs will not be persisted or logged in plaintext.
    model_output_is_sensitive: bool | None = _Field(
        default=None,
        description="When true, model outputs will not be persisted or logged in plaintext.",
    )
    # Industry vertical to use when generating attacks. Optional.
    # When UNSPECIFIED, the data plane falls back to INDUSTRY_DEFAULT.
    industry: "Industry | None" = _Field(
        default=None,
        description="Industry vertical to use when generating attacks. Optional.\nWhen UNSPECIFIED, the data plane falls back to INDUSTRY_DEFAULT.",
    )


class UpdateRedTeamJobStatusRequest(_ProtoModel):
    """
    Request to update red team job status. Internal callback from data plane.
    """

    job_id: str = _Field(default="")
    tenant_id: str = _Field(default="")
    status: "RedTeamJobStatus | None" = _Field(default=None)
    error_message: str = _Field(default="")


class UpdateRedTeamJobStatusResponse(_ProtoModel):
    pass


class GetRedTeamReportRequest(_ProtoModel):
    """
    Request to get the comprehensive report for an adaptive red team job.
    """

    job_id: str = _Field(default="")


class GetRedTeamReportResponse(_ProtoModel):
    report: "RedTeamReport | None" = _Field(default=None)


class UpsertRedTeamReportRequest(_ProtoModel):
    """
    Request to create or update the comprehensive report for a red team job. Internal callback from dataplane.
    """

    job_id: str = _Field(default="")
    report: "RedTeamReport | None" = _Field(default=None)


class UpsertRedTeamReportResponse(_ProtoModel):
    pass


class ResumeRedTeamJobOptions(_ProtoModel):
    """
    ResumeRedTeamJobOptions controls how a paused red team job is resumed.
    """

    # When true, attacks skipped before the pause are retried in addition to
    # continuing work that had not yet run. When false or omitted, previously
    # skipped attacks remain skipped.
    retry_skipped_attacks: bool = _Field(
        default=False,
        description="When true, attacks skipped before the pause are retried in addition to\ncontinuing work that had not yet run. When false or omitted, previously\nskipped attacks remain skipped.",
    )


class RestartRedTeamJobOptions(_ProtoModel):
    """
    RestartRedTeamJobOptions controls which attacks are included in the new job.
    """

    # Filters selecting attacks from the source job. Values use OR semantics. When empty,
    # every attack is run, including attacks that had not started before cancel.
    attack_rerun_filters: "list[AttackRerunFilter]" = _Field(
        default_factory=list,
        description="Filters selecting attacks from the source job. Values use OR semantics. When empty,\nevery attack is run, including attacks that had not started before cancel.",
    )
