# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

# DO NOT EDIT. Generated by protoc-gen-pydantic.
import datetime as _datetime
import re as _re
from dataclasses import dataclass as _dataclass
from enum import Enum as _Enum
from typing import Any as _Any
from typing import Annotated as _Annotated

from pydantic import BeforeValidator as _BeforeValidator
from pydantic import PlainSerializer as _PlainSerializer


def _coerce_int(v):
    return int(v)


ProtoInt64 = _Annotated[
    int,
    _BeforeValidator(_coerce_int),
    _PlainSerializer(lambda v: str(v), return_type=str, when_used="json"),
]

ProtoUInt64 = _Annotated[
    int,
    _BeforeValidator(_coerce_int),
    _PlainSerializer(lambda v: str(v), return_type=str, when_used="json"),
]


def _parse_timestamp(v):
    if isinstance(v, str):
        return _datetime.datetime.fromisoformat(v.replace("Z", "+00:00"))
    if isinstance(v, _datetime.datetime):
        return v
    raise ValueError(f"Cannot parse timestamp from {type(v)}")


def _serialize_timestamp(v):
    if v.tzinfo is None:
        v = v.replace(tzinfo=_datetime.timezone.utc)
    s = v.strftime("%Y-%m-%dT%H:%M:%S")
    us = v.microsecond
    if us:
        s += f".{us:06d}".rstrip("0")
    return s + "Z"


ProtoTimestamp = _Annotated[
    _datetime.datetime,
    _BeforeValidator(_parse_timestamp),
    _PlainSerializer(_serialize_timestamp, return_type=str, when_used="json"),
]


def _parse_duration(v):
    if isinstance(v, str):
        m = _re.match(r"^(-?\d+(?:\.\d+)?)s$", v)
        if not m:
            raise ValueError(f"Invalid duration: {v}")
        return _datetime.timedelta(seconds=float(m.group(1)))
    if isinstance(v, _datetime.timedelta):
        return v
    raise ValueError(f"Cannot parse duration from {type(v)}")


def _serialize_duration(v):
    total = v.total_seconds()
    if total == int(total):
        return f"{int(total)}s"
    return f"{total}s"


ProtoDuration = _Annotated[
    _datetime.timedelta,
    _BeforeValidator(_parse_duration),
    _PlainSerializer(_serialize_duration, return_type=str, when_used="json"),
]


def _require_unique(v):
    if len(v) != len(set(v)):
        raise ValueError("list items must be unique")
    return v


def _make_in_validator(valid_values):
    def _validate(v):
        if v not in valid_values:
            raise ValueError(f"value must be one of {sorted(valid_values)}")
        return v

    return _validate


def _make_not_in_validator(excluded_values):
    def _validate(v):
        if v in excluded_values:
            raise ValueError(f"value must not be one of {sorted(excluded_values)}")
        return v

    return _validate


def _make_cel_validator(pred, message: str):
    def _validate(v):
        if not pred(v):
            raise ValueError(message)
        return v

    return _validate


def _make_cel_str_validator(fn):
    def _validate(v):
        msg = fn(v)
        if msg:
            raise ValueError(msg)
        return v

    return _validate


def _is_unique(v) -> bool:
    return len(v) == len(set(v))


def _cel_matches(pattern: str, s: str) -> bool:
    return bool(_re.search(pattern, s))


@_dataclass(frozen=True)
class _EnumValueOptions:
    deprecated: bool = False
    debug_redact: bool = False
    value_visibility: _Any | None = None


class _ProtoEnum(str, _Enum):
    number: int
    _options_: _EnumValueOptions

    def __new__(
        cls,
        value: str,
        number: int = 0,
        options: _EnumValueOptions | None = None,
    ):
        obj = str.__new__(cls, value)
        obj._value_ = value
        obj.number = number
        obj._options_ = options if options is not None else _EnumValueOptions()
        return obj

    @property
    def options(self) -> _EnumValueOptions:
        return self._options_
