# DO NOT EDIT. Generated by protoc-gen-pydantic.

from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field

from ._proto_types import ProtoTimestamp, _ProtoEnum


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class ConnectorStatus(_ProtoEnum):
    """
    ConnectorStatus represents the current state of a connector.
    """

    NONE_CONNECTOR_STATUS = ("NONE_CONNECTOR_STATUS", 0)
    ACTIVE = ("ACTIVE", 1)
    # Connector is active and connected
    PENDING_INSTALLATION = ("PENDING_INSTALLATION", 2)
    # Connector is being installed
    PENDING_CONNECTION = ("PENDING_CONNECTION", 3)
    # Connector is installed but not yet connected
    UNRESPONSIVE = ("UNRESPONSIVE", 4)
    # Connector is not responding
    DELETED = ("DELETED", 5)
    # Connector has been deleted


class ContentType(_ProtoEnum):
    """
    ContentType represents the type of content in a deployment or upgrade guide.
    """

    NONE_CONTENT_TYPE = ("NONE_CONTENT_TYPE", 0)
    # Default value, should not be used
    COMMAND = ("COMMAND", 1)
    # Content is a command to execute
    MESSAGE = ("MESSAGE", 2)
    # Content is a message to display


class StepName(_ProtoEnum):
    """
    StepName represents the names of steps in the deployment or upgrade process.
    """

    NONE_STEP_NAME = ("NONE_STEP_NAME", 0)
    # Default value, should not be used
    LOGIN = ("LOGIN", 1)
    # Login step, used in deployment guide, upgrade guide
    INSTALL_PREFLIGHT_PLUGIN = ("INSTALL_PREFLIGHT_PLUGIN", 2)
    # Preflight step, used in deployment guide, upgrade guide
    DOWNLOAD_VALUES_FILE = ("DOWNLOAD_VALUES_FILE", 3)
    # Step to download values file, used in deployment guide
    EDIT_VALUES_FILE = ("EDIT_VALUES_FILE", 4)
    # Step to edit values file, used in deployment guide
    INSTALL_CHART = ("INSTALL_CHART", 5)
    # Step to install the chart, used in deployment guide
    RUN_PREFLIGHT_CHECKS = ("RUN_PREFLIGHT_CHECKS", 6)
    # Step to run preflight checks, used in upgrade guide
    INSTALL_LATEST_VERSION = ("INSTALL_LATEST_VERSION", 7)
    # Step to install the latest version, used in upgrade guide
    CREATE_NAMESPACE = ("CREATE_NAMESPACE", 8)
    # Step to create namespace, used in deployment guide
    SET_NAMESPACE_CONTEXT = ("SET_NAMESPACE_CONTEXT", 9)
    # Step to set namespace context, used in upgrade guide


class ScriptType(_ProtoEnum):
    """
    ScriptType represents the type of bash script to generate.
    """

    NONE_SCRIPT_TYPE = ("NONE_SCRIPT_TYPE", 0)
    # Default value, should not be used
    INSTALL_SCRIPT = ("INSTALL_SCRIPT", 1)
    # Script for fresh installation
    UPGRADE_SCRIPT = ("UPGRADE_SCRIPT", 2)
    # Script for upgrading existing installation
    EDIT_SERVICES_SCRIPT = ("EDIT_SERVICES_SCRIPT", 3)
    # Script for editing services configuration


class HybridEnvironment(_ProtoEnum):
    """
    HybridEnvironment represents the environment in which a connector is deployed.
    """

    NONE_HYBRID_ENVIRONMENT = ("NONE_HYBRID_ENVIRONMENT", 0)
    AWS_EKS = ("AWS_EKS", 1)
    REDHAT_OPEN_SHIFT = ("REDHAT_OPEN_SHIFT", 2)
    AZURE_KUBERNETES_SERVICE = ("AZURE_KUBERNETES_SERVICE", 3)
    GOOGLE_KUBERNETES_ENGINE = ("GOOGLE_KUBERNETES_ENGINE", 4)
    PRIVATE = ("PRIVATE", 5)
    # Private connector (proxy relay use case)


class AIDefenseService(_ProtoEnum):
    """
    AIDefenseService represents the type of AI Defense service supported by a connector.
    """

    NONE_AI_DEFENSE_SERVICE = ("NONE_AI_DEFENSE_SERVICE", 0)
    VALIDATION = ("VALIDATION", 1)
    RUNTIME = ("RUNTIME", 2)
    MCD = ("MCD", 3)
    SUPPLY_CHAIN = ("SUPPLY_CHAIN", 4)


class DeploymentStatus(_ProtoEnum):
    """
    DeploymentStatus represents the operator and AI Defense deployment lifecycle
    """

    NONE_DEPLOYMENT_STATUS = ("NONE_DEPLOYMENT_STATUS", 0)
    OPERATOR_NOT_INSTALLED = ("OPERATOR_NOT_INSTALLED", 1)
    # Operator is not installed
    OPERATOR_INSTALLED = ("OPERATOR_INSTALLED", 2)
    # Operator is installed
    DEPLOYMENT_INSTALLING = ("DEPLOYMENT_INSTALLING", 3)
    # AI Defense deployment in progress
    DEPLOYMENT_UPGRADING = ("DEPLOYMENT_UPGRADING", 4)
    # AI Defense upgrade in progress
    DEPLOYMENT_INSTALLED = ("DEPLOYMENT_INSTALLED", 5)
    # AI Defense is deployed and running
    DEPLOYMENT_ERROR = ("DEPLOYMENT_ERROR", 6)
    # Deployment encountered an error


class AwsConfiguration(_ProtoModel):
    """
    Environment-specific configurations
    """

    # Enable AWS Bedrock integration for AI services
    bedrock_enabled: bool = _Field(
        default=False,
        description="Enable AWS Bedrock integration for AI services",
    )
    # AWS account ID
    aws_account_id: str = _Field(
        default="",
        description="AWS account ID",
    )


class CreateConnectorRequest(_ProtoModel):
    """
    Request to create a new connector.
    """

    # Human-readable name for the connector.
    # Must be unique within the tenant.
    name: str = _Field(
        default="",
        description="Human-readable name for the connector.\nMust be unique within the tenant.",
    )
    # Environment in which the connector is deployed.
    # Must not be NONE_HYBRID_ENVIRONMENT.
    environment: "HybridEnvironment | None" = _Field(
        default=None,
        description="Environment in which the connector is deployed.\nMust not be NONE_HYBRID_ENVIRONMENT.",
    )
    # services types supported by the connector.
    # Each service must not be NONE_AI_DEFENSE_SERVICE.
    services: "list[AIDefenseService]" = _Field(
        default_factory=list,
        description="services types supported by the connector.\nEach service must not be NONE_AI_DEFENSE_SERVICE.",
    )
    # Environment-specific configurations (optional, set based on the selected environment)
    aws_config: "AwsConfiguration | None" = _Field(
        default=None,
        description="Environment-specific configurations (optional, set based on the selected environment)",
    )
    # Future environment configs can be added here as needed
    # AzureConfiguration azure_config = 5;
    # RedHatConfiguration redhat_config = 6;
    # GcpConfiguration gcp_config = 7;
    # URL for the Kubernetes OIDC provider for this connector deployment.
    token_issuer_url: str = _Field(
        default="",
        description="URL for the Kubernetes OIDC provider for this connector deployment.",
    )
    # ID of the Kubernetes cluster for this connector deployment.
    cluster_id: str = _Field(
        default="",
        description="ID of the Kubernetes cluster for this connector deployment.",
    )
    # JSON Web Key Set (JWKS) for OIDC token validation.
    jwks: str = _Field(
        default="",
        description="JSON Web Key Set (JWKS) for OIDC token validation.",
    )


class CreateConnectorResponse(_ProtoModel):
    """
    Response containing the created connector's ID.
    """

    # System-generated unique identifier for the connector.
    connector_id: str = _Field(
        default="",
        description="System-generated unique identifier for the connector.",
    )


class GetConnectorRequest(_ProtoModel):
    """
    Request to retrieve a specific connector.
    """

    # The unique identifier of the connector to retrieve.
    connector_id: str = _Field(
        default="",
        description="The unique identifier of the connector to retrieve.",
    )


class Connector(_ProtoModel):
    """
    Represents an AI Defense connector instance.
    """

    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    # Unique identifier for the connector.
    id_: str = _Field(
        default="",
        description="Unique identifier for the connector.",
        alias="id",
    )
    # Human-readable name of the connector.
    name: str = _Field(
        default="",
        description="Human-readable name of the connector.",
    )
    # Timestamp when the connector was created.
    created_at: ProtoTimestamp | None = _Field(
        default=None,
        description="Timestamp when the connector was created.",
    )
    # Timestamp of the last activity from this connector.
    last_active: ProtoTimestamp | None = _Field(
        default=None,
        description="Timestamp of the last activity from this connector.",
    )
    # Current status of the connector.
    status: "ConnectorStatus | None" = _Field(
        default=None,
        description="Current status of the connector.",
    )
    # Version identifier of the connector software.
    version: str = _Field(
        default="",
        description="Version identifier of the connector software.",
    )
    # Environment type for the connector.
    environment: "HybridEnvironment | None" = _Field(
        default=None,
        description="Environment type for the connector.",
    )
    # services types for the connector.
    services: "list[AIDefenseService]" = _Field(
        default_factory=list,
        description="services types for the connector.",
    )
    # Environment-specific configurations (optional, set based on the selected environment)
    aws_config: "AwsConfiguration | None" = _Field(
        default=None,
        description="Environment-specific configurations (optional, set based on the selected environment)",
    )
    # Future environment configs can be added here as needed
    # AzureConfiguration azure_config = 10;
    # RedHatConfiguration redhat_config = 11;
    # GcpConfiguration gcp_config = 12;
    # URL for the Kubernetes OIDC provider for this connector deployment.
    token_issuer_url: str = _Field(
        default="",
        description="URL for the Kubernetes OIDC provider for this connector deployment.",
    )
    # ID of the Kubernetes cluster for this connector deployment.
    cluster_id: str = _Field(
        default="",
        description="ID of the Kubernetes cluster for this connector deployment.",
    )
    # Deployment status for this connector (operator and AI Defense lifecycle)
    deployment_status: "DeploymentStatus | None" = _Field(
        default=None,
        description="Deployment status for this connector (operator and AI Defense lifecycle)",
    )
    # Deployment config with display-ready labels (populated from saved config)
    deployment_config: "list[ConfigFieldSummary]" = _Field(
        default_factory=list,
        description="Deployment config with display-ready labels (populated from saved config)",
    )
    # JSON Web Key Set (JWKS) for OIDC token validation.
    jwks: str = _Field(
        default="",
        description="JSON Web Key Set (JWKS) for OIDC token validation.",
    )
    # Indicates whether the proxy relay (grpctunnel) path is available for this connector.
    # Set to true by cloud_gw when a proxyrelayclient tunnel connection is established.
    is_proxy_relay_available: bool = _Field(
        default=False,
        description="Indicates whether the proxy relay (grpctunnel) path is available for this connector.\nSet to true by cloud_gw when a proxyrelayclient tunnel connection is established.",
    )


class ConnectorsPerTenant(_ProtoModel):
    """
    All connectors per tenant.
    """

    tenant_id: str = _Field(default="")
    connectors: "list[Connector]" = _Field(
        default_factory=list,
    )


class GetAllConnectorsResponse(_ProtoModel):
    """
    Response containing all connectors per tenant.
    """

    connectors_per_tenant: "list[ConnectorsPerTenant]" = _Field(
        default_factory=list,
    )


class ListConnectorsRequest(_ProtoModel):
    """
    Request to list connectors with pagination support.
    """

    # Number of records to retrieve
    limit: int = _Field(
        default=0,
        description="Number of records to retrieve",
    )
    # Offset for pagination
    offset: int = _Field(
        default=0,
        description="Offset for pagination",
    )


class ListConnectorsResponse(_ProtoModel):
    """
    Response containing a list of connectors.
    """

    # List of connector objects.
    connectors: "list[Connector]" = _Field(
        default_factory=list,
        description="List of connector objects.",
    )
    # Total number of connectors in the response
    total: int = _Field(
        default=0,
        description="Total number of connectors in the response",
    )
    # Offset for the next set of connectors to retrieve
    next_offset: int = _Field(
        default=0,
        description="Offset for the next set of connectors to retrieve",
    )


class DeleteConnectorRequest(_ProtoModel):
    """
    Request to delete a connector.
    """

    # The unique identifier of the connector to delete.
    connector_id: str = _Field(
        default="",
        description="The unique identifier of the connector to delete.",
    )


class DeleteConnectorResponse(_ProtoModel):
    """
    Empty response for delete operations.
    """

    pass


class UpdateConnectorRequest(_ProtoModel):
    # The unique identifier of the connector to update.
    connector_id: str = _Field(
        default="",
        description="The unique identifier of the connector to update.",
    )
    # Human-readable name for the connector.
    # Must be unique within the tenant.
    name: str = _Field(
        default="",
        description="Human-readable name for the connector.\nMust be unique within the tenant.",
    )
    # services types supported by the connector.
    # Each service must not be NONE_AI_DEFENSE_SERVICE.
    services: "list[AIDefenseService]" = _Field(
        default_factory=list,
        description="services types supported by the connector.\nEach service must not be NONE_AI_DEFENSE_SERVICE.",
    )
    # Environment-specific configurations (optional, set based on the selected environment)
    aws_config: "AwsConfiguration | None" = _Field(
        default=None,
        description="Environment-specific configurations (optional, set based on the selected environment)",
    )
    # Future environment configs can be added here as needed
    # AzureConfiguration azure_config = 5;
    # RedHatConfiguration redhat_config = 6;
    # GcpConfiguration gcp_config = 7;
    # URL for the Kubernetes OIDC provider for this connector deployment.
    token_issuer_url: str = _Field(
        default="",
        description="URL for the Kubernetes OIDC provider for this connector deployment.",
    )
    # ID of the Kubernetes cluster for this connector deployment.
    cluster_id: str = _Field(
        default="",
        description="ID of the Kubernetes cluster for this connector deployment.",
    )
    # JSON Web Key Set (JWKS) for OIDC token validation.
    jwks: str = _Field(
        default="",
        description="JSON Web Key Set (JWKS) for OIDC token validation.",
    )


class UpdateConnectorStatusAndTimeRequest(_ProtoModel):
    # The unique identifier of the connector to update.
    connector_id: str = _Field(
        default="",
        description="The unique identifier of the connector to update.",
    )
    # The status of the connector. In case there is any error in the connection
    status: "ConnectorStatus | None" = _Field(
        default=None,
        description="The status of the connector. In case there is any error in the connection",
    )
    # Timestamp of the last activity from this connector.
    last_active: ProtoTimestamp | None = _Field(
        default=None,
        description="Timestamp of the last activity from this connector.",
    )


class UpdateConnectorVersionRequest(_ProtoModel):
    # The unique identifier of the connector to update.
    connector_id: str = _Field(
        default="",
        description="The unique identifier of the connector to update.",
    )
    # Version identifier of the connector software.
    version: str = _Field(
        default="",
        description="Version identifier of the connector software.",
    )


class UpdateConnectorIsProxyRelayAvailableRequest(_ProtoModel):
    # The unique identifier of the connector to update.
    connector_id: str = _Field(
        default="",
        description="The unique identifier of the connector to update.",
    )
    # No bool field — calling this RPC always sets is_proxy_relay_available to true.
    # Once available, the flag is never unset.


class GetLatestReleaseRequest(_ProtoModel):
    """
    Request to get the latest release information.
    """

    # If set, indicates whether to check for incremental update version for the connector.
    # In case we could not migrate to the latest version directly.
    check_incremental_update: bool = _Field(
        default=False,
        description="If set, indicates whether to check for incremental update version for the connector.\nIn case we could not migrate to the latest version directly.",
    )


class Release(_ProtoModel):
    """
    Represents a release of the AI Defense system.
    """

    # Semantic version of the release (e.g., "1.0.0").
    version: str = _Field(
        default="",
        description='Semantic version of the release (e.g., "1.0.0").',
    )
    # Release notes for the version, this might be empty
    release_notes: str = _Field(
        default="",
        description="Release notes for the version, this might be empty",
    )
    # When the release was published.
    release_date: ProtoTimestamp | None = _Field(
        default=None,
        description="When the release was published.",
    )
    # Sequence number for ordering releases. Higher numbers indicate more recent releases.
    # this is widely used by replicated. version is only assigned to a release when it is assigned to a connector.
    sequence: int = _Field(
        default=0,
        description="Sequence number for ordering releases. Higher numbers indicate more recent releases.\nthis is widely used by replicated. version is only assigned to a release when it is assigned to a connector.",
    )
    # channel sequence number for the latest release
    channel_sequence: int = _Field(
        default=0,
        description="channel sequence number for the latest release",
    )


class GetLatestReleaseResponse(_ProtoModel):
    """
    Response containing latest release information.
    """

    # Details about the latest release.
    release: "Release | None" = _Field(
        default=None,
        description="Details about the latest release.",
    )
    # Whether an update is available.
    update_required: bool = _Field(
        default=False,
        description="Whether an update is available.",
    )
    # Whether the connector version is outdated, and is no more supported
    is_version_outdated: bool = _Field(
        default=False,
        description="Whether the connector version is outdated, and is no more supported",
    )
    # list of connector id's that are outdated or upgrade is available
    outdated_connector_ids: list[str] = _Field(
        default_factory=list,
        description="list of connector id's that are outdated or upgrade is available",
    )
    # list of connector id's that are not supported
    unsupported_connector_ids: list[str] = _Field(
        default_factory=list,
        description="list of connector id's that are not supported",
    )
    # list of connector id's where operator is no longer supported
    operator_unsupported_connector_ids: list[str] = _Field(
        default_factory=list,
        description="list of connector id's where operator is no longer supported",
    )
    # list of connector id's where operator upgrade is required
    operator_upgrade_required_connector_ids: list[str] = _Field(
        default_factory=list,
        description="list of connector id's where operator upgrade is required",
    )


class GetConnectorGuideRequest(_ProtoModel):
    """
    Request to get deployment guide for a connector.
    """

    # The unique identifier of the connector.
    connector_id: str = _Field(
        default="",
        description="The unique identifier of the connector.",
    )


class GuideResponse(_ProtoModel):
    """
    Instructions for deploying or updating a connector.
    """

    class ContentMeta(_ProtoModel):
        """
        Metadata about a piece of content in the guide.
        """

        # The actual content (e.g., command, message).
        content: str = _Field(
            default="",
            description="The actual content (e.g., command, message).",
        )
        # Type of content (e.g., "command", "message").
        content_type: "ContentType | None" = _Field(
            default=None,
            description='Type of content (e.g., "command", "message").',
        )

    class Step(_ProtoModel):
        """
        A step in the deployment/update process.
        """

        # Name of the step (matches UI step names).
        name: "StepName | None" = _Field(
            default=None,
            description="Name of the step (matches UI step names).",
        )
        # The content making up this step.
        content_meta: "list[GuideResponse.ContentMeta]" = _Field(
            default_factory=list,
            description="The content making up this step.",
        )

    # Ordered list of steps to complete the process.
    steps: "list[GuideResponse.Step]" = _Field(
        default_factory=list,
        description="Ordered list of steps to complete the process.",
    )


class GetConnectorUpgradeGuideRequest(_ProtoModel):
    """
    Request to get upgrade guide for a connector.
    """

    # The unique identifier of the connector.
    connector_id: str = _Field(
        default="",
        description="The unique identifier of the connector.",
    )


class GetConnectorScriptRequest(_ProtoModel):
    """
    Request to get bash script for a connector.
    """

    # The unique identifier of the connector.
    connector_id: str = _Field(
        default="",
        description="The unique identifier of the connector.",
    )
    # Type of script to generate (install, upgrade, or edit services).
    # Must not be NONE_SCRIPT_TYPE.
    script_type: "ScriptType | None" = _Field(
        default=None,
        description="Type of script to generate (install, upgrade, or edit services).\nMust not be NONE_SCRIPT_TYPE.",
    )


class GetConnectorScriptResponse(_ProtoModel):
    """
    Response containing the generated bash script.
    """

    # The generated bash script content.
    script_content: str = _Field(
        default="",
        description="The generated bash script content.",
    )


class GetClusterGuideResponse(_ProtoModel):
    """
    GetClusterSetupGuideResponse is the response for GetClusterSetupGuide
    """

    cloud_gw_endpoint: str = _Field(default="")


class VersionlessConnector(_ProtoModel):
    """
    Represents connector information without runtime version field.
    This is used for internal APIs that retrieve connector data directly from the database.
    """

    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    # Unique identifier for the connector.
    id_: str = _Field(
        default="",
        description="Unique identifier for the connector.",
        alias="id",
    )
    # Human-readable name of the connector.
    name: str = _Field(
        default="",
        description="Human-readable name of the connector.",
    )
    # Timestamp when the connector was created.
    created_at: ProtoTimestamp | None = _Field(
        default=None,
        description="Timestamp when the connector was created.",
    )
    # Timestamp of the last activity from this connector.
    last_active: ProtoTimestamp | None = _Field(
        default=None,
        description="Timestamp of the last activity from this connector.",
    )
    # Current status of the connector.
    status: "ConnectorStatus | None" = _Field(
        default=None,
        description="Current status of the connector.",
    )
    # Environment type for the connector.
    environment: "HybridEnvironment | None" = _Field(
        default=None,
        description="Environment type for the connector.",
    )
    # services types for the connector.
    services: "list[AIDefenseService]" = _Field(
        default_factory=list,
        description="services types for the connector.",
    )
    # Environment-specific configurations (optional, set based on the selected environment)
    aws_config: "AwsConfiguration | None" = _Field(
        default=None,
        description="Environment-specific configurations (optional, set based on the selected environment)",
    )
    # Future environment configs can be added here as needed
    # AzureConfiguration azure_config = 9;
    # RedHatConfiguration redhat_config = 10;


class GetVersionlessConnectorByIdsRequest(_ProtoModel):
    """
    Request to get versionless connectors by their IDs.
    """

    # List of connector IDs to retrieve.
    connector_ids: list[str] = _Field(
        default_factory=list,
        description="List of connector IDs to retrieve.",
    )


class GetVersionlessConnectorByIdsResponse(_ProtoModel):
    """
    Response containing versionless connector information for the requested IDs.
    """

    # List of versionless connector information objects.
    connectors: "list[VersionlessConnector]" = _Field(
        default_factory=list,
        description="List of versionless connector information objects.",
    )


class CreateOnpremCustomerRequest(_ProtoModel):
    """
    Request to create an onprem customer.
    """

    pass


class CreateOnpremCustomerResponse(_ProtoModel):
    """
    Response containing the created onprem customer information.
    """

    # Onprem customer ID.
    onprem_customer_id: str = _Field(
        default="",
        description="Onprem customer ID.",
    )


class HasOnpremCustomerResponse(_ProtoModel):
    """
    Response having details if onprem customer exists or not.
    """

    has_customer: bool = _Field(default=False)


class GetOperatorInstallInstructionsRequest(_ProtoModel):
    """
    Request to get operator install instructions for a connector.
    """

    # The unique identifier of the connector.
    connector_id: str = _Field(
        default="",
        description="The unique identifier of the connector.",
    )


class GetOperatorInstallInstructionsResponse(_ProtoModel):
    """
    Response containing operator installation instructions script.
    """

    # Python script content for operator installation
    script_content: str = _Field(
        default="",
        description="Python script content for operator installation",
    )


class GetOperatorUpgradeInstructionsRequest(_ProtoModel):
    """
    Request to get operator upgrade instructions for a connector.
    """

    # The unique identifier of the connector.
    connector_id: str = _Field(
        default="",
        description="The unique identifier of the connector.",
    )


class GetOperatorUpgradeInstructionsResponse(_ProtoModel):
    """
    Response containing operator upgrade instructions script.
    """

    # Python script content for operator upgrade
    script_content: str = _Field(
        default="",
        description="Python script content for operator upgrade",
    )


class InstallAIDefenseRequest(_ProtoModel):
    """
    Request to install AI Defense using operator.
    """

    # The unique identifier of the connector.
    connector_id: str = _Field(
        default="",
        description="The unique identifier of the connector.",
    )


class InstallAIDefenseResponse(_ProtoModel):
    """
    Response for AI Defense installation operation.
    """

    # Status message
    message: str = _Field(
        default="",
        description="Status message",
    )
    # Whether the installation was initiated successfully
    is_successful: bool = _Field(
        default=False,
        description="Whether the installation was initiated successfully",
    )


class UpgradeAIDefenseRequest(_ProtoModel):
    """
    Request to upgrade AI Defense using operator.
    """

    # The unique identifier of the connector.
    connector_id: str = _Field(
        default="",
        description="The unique identifier of the connector.",
    )


class UpgradeAIDefenseResponse(_ProtoModel):
    """
    Response for AI Defense upgrade operation.
    """

    # Status message
    message: str = _Field(
        default="",
        description="Status message",
    )
    # Whether the upgrade was initiated successfully
    is_successful: bool = _Field(
        default=False,
        description="Whether the upgrade was initiated successfully",
    )


class ConfigFieldOption(_ProtoModel):
    """
    ConfigFieldOption represents a selectable option for a config field
    """

    # The actual value to be used
    value: str = _Field(
        default="",
        description="The actual value to be used",
    )
    # Display label for the option
    display_label: str = _Field(
        default="",
        description="Display label for the option",
    )
    # Optional description for the option
    description: str = _Field(
        default="",
        description="Optional description for the option",
    )


class VisibilityCondition(_ProtoModel):
    """
    VisibilityCondition defines when a field should be visible based on parent field value
    """

    # Parent field key to check
    parent_key: str = _Field(
        default="",
        description="Parent field key to check",
    )
    # Field is visible when parent value is one of these (OR within condition)
    values: list[str] = _Field(
        default_factory=list,
        description="Field is visible when parent value is one of these (OR within condition)",
    )


class ConfigFieldDefinition(_ProtoModel):
    """
    ConfigFieldDefinition defines metadata for a single config field
    """

    # Unique field identifier (e.g., "gpu_selection")
    key: str = _Field(
        default="",
        description='Unique field identifier (e.g., "gpu_selection")',
    )
    # Display label (e.g., "GPU Type")
    display_label: str = _Field(
        default="",
        description='Display label (e.g., "GPU Type")',
    )
    # Help text describing the field
    description: str = _Field(
        default="",
        description="Help text describing the field",
    )
    # Default value as string
    default_value: str = _Field(
        default="",
        description="Default value as string",
    )
    # Available options for dropdown fields (optional)
    options: "list[ConfigFieldOption]" = _Field(
        default_factory=list,
        description="Available options for dropdown fields (optional)",
    )
    # Whether the field is required
    required: bool = _Field(
        default=False,
        description="Whether the field is required",
    )
    # UI input type hint: "text", "number", "toggle", "dropdown"
    input_type: str = _Field(
        default="",
        description='UI input type hint: "text", "number", "toggle", "dropdown"',
    )
    # Visibility conditions - all must be true (AND logic between conditions)
    visibility_conditions: "list[VisibilityCondition]" = _Field(
        default_factory=list,
        description="Visibility conditions - all must be true (AND logic between conditions)",
    )


class ConfigFieldDefinitions(_ProtoModel):
    """
    ConfigFieldDefinitions contains all available config field definitions
    """

    # List of available config field definitions
    fields: "list[ConfigFieldDefinition]" = _Field(
        default_factory=list,
        description="List of available config field definitions",
    )


class ConfigFieldValue(_ProtoModel):
    """
    ConfigFieldValue represents a single config field value set by user
    """

    # Field key (must match ConfigFieldDefinition.key)
    key: str = _Field(
        default="",
        description="Field key (must match ConfigFieldDefinition.key)",
    )
    # Value stored as string (type is derived from ConfigFieldDefinition)
    value: str = _Field(
        default="",
        description="Value stored as string (type is derived from ConfigFieldDefinition)",
    )


class ConfigFieldSummary(_ProtoModel):
    """
    ConfigFieldSummary represents a config field with display-ready values for Connector response
    """

    # Field key (e.g., "gpu_selection")
    key: str = _Field(
        default="",
        description='Field key (e.g., "gpu_selection")',
    )
    # Raw value (e.g., "nvidia_h100")
    value: str = _Field(
        default="",
        description='Raw value (e.g., "nvidia_h100")',
    )
    # Display label (e.g., "GPU Type")
    display_label: str = _Field(
        default="",
        description='Display label (e.g., "GPU Type")',
    )
    # Display value (e.g., "NVIDIA H100")
    display_value: str = _Field(
        default="",
        description='Display value (e.g., "NVIDIA H100")',
    )


class GetDeploymentConfigRequest(_ProtoModel):
    """
    Request to get deployment config definitions and current values for a connector
    """

    # Connector ID (required) - returns current values for the connector
    connector_id: str = _Field(
        default="",
        description="Connector ID (required) - returns current values for the connector",
    )


class GetDeploymentConfigResponse(_ProtoModel):
    """
    Response containing deployment config definitions and current values
    """

    # Available config field definitions
    config: "ConfigFieldDefinitions | None" = _Field(
        default=None,
        description="Available config field definitions",
    )
    # Current config field values for the connector
    # Values are: last saved values > defaults from config
    current_values: "list[ConfigFieldValue]" = _Field(
        default_factory=list,
        description="Current config field values for the connector\nValues are: last saved values > defaults from config",
    )


class SetDeploymentConfigRequest(_ProtoModel):
    """
    Request to set connector deployment config values
    """

    # The unique identifier of the connector
    connector_id: str = _Field(
        default="",
        description="The unique identifier of the connector",
    )
    # Config field values to set
    values: "list[ConfigFieldValue]" = _Field(
        default_factory=list,
        description="Config field values to set",
    )


class SetDeploymentConfigResponse(_ProtoModel):
    """
    Response for setting connector deployment config values
    """

    # Whether the operation was successful
    is_success: bool = _Field(
        default=False,
        description="Whether the operation was successful",
    )
    # Status message
    message: str = _Field(
        default="",
        description="Status message",
    )
